# Generated by Django 5.2.4 on 2025-08-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
