# Generated by Django 5.2.4 on 2025-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_note_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
