# Generated by Django 5.2.4 on 2025-08-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_is_archived_note_is_pinned_note_is_trashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_pinned',
        ),
    ]
