# Generated by Django 5.2.4 on 2025-08-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
